import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

// const roboto = localFont({
//   src: "../assets/fonts/Roboto.tff",
//   variable: "--font-roboto",
//   weight: "100 900",
// });

const workSans = localFont({
  src: "../assets/fonts/WorkSans.ttf",
  variable: "--font-work-sans",
  weight: "100 900"
})

const avenirNext = localFont({
  src: "../assets/fonts/AvenirNext.otf",
  variable: "--font-avenir-next",
  weight: "100 900"
})
const avenirNextSans = localFont({
  src: "../assets/fonts/AvenirNextSans.otf",
  variable: "--font-avenir-sans",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Lendsqr Project",
  description: "Generated by Kemdinachi Lyonnet Ifeanyi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${avenirNext.variable} ${avenirNextSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
